drop schema tims;

CREATE SCHEMA IF NOT EXISTS `tims`;

USE `tims` ;

DROP TABLE IF EXISTS `CUSTOMERS`;
DROP TABLE IF EXISTS `ITEMS`;
DROP TABLE IF EXISTS `ORDERS`;
DROP TABLE IF EXISTS `ORDER_ITEMS`;

CREATE TABLE IF NOT EXISTS `CUSTOMERS` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `first_name` VARCHAR(40) DEFAULT NULL,
    `surname` VARCHAR(40) DEFAULT NULL,
    PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `ITEMS` (
    `item_ID` INT(11) NOT NULL AUTO_INCREMENT,
    `item_name` VARCHAR(40) DEFAULT NULL,
    `item_price` DOUBLE DEFAULT NULL,
    PRIMARY KEY (`item_ID`)
);

CREATE TABLE IF NOT EXISTS `ORDERS` (
    `order_ID` INT(11) NOT NULL AUTO_INCREMENT,
    `fk_customer_id` INT NOT NULL,
    `order_date` VARCHAR(50) DEFAULT NULL,
    PRIMARY KEY (`order_ID`),
    FOREIGN KEY (`fk_customer_id`) REFERENCES CUSTOMERS(`id`)
);

CREATE TABLE IF NOT EXISTS `ORDER_ITEMS` (
    `orderdetails_id` INT(11) NOT NULL AUTO_INCREMENT,
    `fk_order_id` INT NOT NULL,
    `fk_item_id` INT NOT NULL,
    PRIMARY KEY (`orderdetails_id`),
    FOREIGN KEY (`fk_order_id`) REFERENCES ORDERS(`order_ID`),
	FOREIGN KEY (`fk_item_id`) REFERENCES ITEMS(`item_ID`)
);

